[workspace]
resolver = "2"

members = [
  "crates/service-utils",
  "crates/context-aware-config",
  "crates/superposition_client",
  "crates/cac_client",
  "crates/superposition_client_integration_example",
  "crates/frontend"
]


[[workspace.metadata.leptos]]
output-name = "frontend"
bin-package = "context-aware-config"
lib-package = "frontend"
assets-dir = "crates/frontend/assets"
style-file = "frontend/style/output.css"
site-root = "crates/frontend"

[workspace.metadata.leptos.style]
# Main style file. If scss or sass then it will be compiled to css.
# the parent folder will be watched for changes
file = "style/output.css"
# A https://browsersl.ist query
browserquery = "defaults"

[workspace.dependencies]
dotenv = "0.15.0"
actix = "0.13.0"
actix-web = "4.0.0"
diesel = { version = "2.1.0", features = ["postgres", "r2d2", "serde_json", "chrono", "uuid", "postgres_backend"] }
env_logger = "0.8"
log = { version="0.4.20", features = ["kv_unstable_serde"] }
serde = {version = "^1", features = ["derive"]}
serde_json = {version = "1.0"}
derive_more = "^0.99"
base64 = "0.21.2"
urlencoding = "~2.1.2"
chrono = { version = "0.4.26", features = ["serde"] }
uuid = {version = "1.3.4", features = ["v4", "serde"]}
reqwest = { version = "0.11.18", features = ["json"]}
jsonschema = "~0.17"
jsonlogic = "0.5.1"
json-patch = "1.0.0"
rs-snowflake = "0.6.0"
rusoto_kms = "0.48.0"
rusoto_signature = "0.48.0"
bytes = "1.4.0"
rusoto_core = "0.48.0"
rand = "0.8.5"
once_cell = { version = "1.18.0" }
anyhow = { version = "1.0", default-features = false }
strum_macros = "^0.24"
strum = {version = "^0.24"}
# juspay dependencies
dashboard-auth = { git = "ssh://git@ssh.bitbucket.juspay.net/picaf/sdk-rs-utils.git", tag = "v1.5.0"}