[package]
name = "cac_client"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = { workspace = true }
derive_more = { workspace = true }
actix-web = { workspace = true }
chrono = { workspace = true }
jsonlogic = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
json-patch = { workspace = true }
