[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dotenv = { workspace = true }
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", optional = true, features = ["macros"] }
console_error_panic_hook = "0.1"
cfg-if = "1"
http = { version = "0.2", optional = true }
leptos = { version = "0.5.2" }
leptos_meta = { version = "0.5.2" }
leptos_actix = { version = "0.5.2", optional = true }
leptos_router = { version = "0.5.2" }
wasm-bindgen = "=0.2.89"
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
web-sys = "0.3.64"
futures = "0.3"
derive_more = { workspace = true }
anyhow = { workspace = true }
chrono = {workspace = true }
strum_macros = { workspace = true }
strum = { workspace = true }
js-sys = "0.3.65"


[features]
csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr"]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = [
  "dep:actix-files",
  "dep:actix-web",
  "dep:leptos_actix",
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
]